name: vsslagent
version: '1.2' 
summary: VSSL REST api
description: VSSL REST api, remote control, and health monitor
grade: stable
confinement: strict
apps:
   agent:
      command: main-linux
      daemon: simple
      restart-condition: always 
      plugs: [network]
parts:
  vssl:
    source: .
    plugin: dump
